// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (Feature | Grid | Page | Teaser)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Feature | Grid | Page | Teaser)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}
